# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jira',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/jira',
                'lib_path': 'jira'},
  'syms': {'jira.core': {'jira.core.foo': ('core.html#foo', 'jira/core.py')}}}
