name: Deploy to GitHub Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JIRA_INSTANCE: ${{ secrets.JIRA_INSANCE }}
      JIRA_PAT: ${{ secrets.JIRA_PAT }}  
    steps: 
      - uses: actions/checkout@v4
      - uses: fastai/workflows/quarto-ghp@master