name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JIRA_INSTANCE: ${{ secrets.JIRA_INSTANCE }}
      JIRA_PAT: ${{ secrets.JIRA_PAT }}
    steps: [uses: fastai/workflows/nbdev-ci@master]
